# Generated by Django 5.2.7 on 2025-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="unit_price",
        ),
    ]
